<?php

declare(strict_types=1);

namespace Remediate\Tests\Support;

use Composer\Composer;
use Remediate\Engine\Plan\Plan;
use Remediate\Output\CycloneDxRenderer;
use Remediate\Output\GitLabRenderer;
use Remediate\Output\LockLineIndex;
use Remediate\Output\ReportFormat;

/**
 * The example reports stored under each fixture's reports/ directory, rendered in one place.
 *
 * bin/run-fixture.php --write-reports writes them and FixtureTest compares them with a fresh render,
 * both through render(), so the stored copy cannot drift from what the tool prints without a test
 * failing. The Composer release they were recorded with is stored beside them: an older Composer
 * (the Composer-version matrix) legitimately recommends different commands, so the comparison runs
 * only on the recorded minor release, and a newer one fails until the reports are regenerated.
 */
final class FixtureReports
{
    public const COMPOSER_VERSION_FILE = FixtureRunner::FIXTURE_ROOT . '/reports-composer-version.txt';

    /**
     * @return array<string, string> file name under reports/ => contents
     */
    public static function render(Plan $plan, string $fixtureDir): array
    {
        $name = basename($fixtureDir);
        $stable = $plan->withMetadata([
            'project' => $name,
            'advisory_source' => 'advisory snapshot advisories.json',
            'analysis_timestamp' => '(fixture)',
            'composer_json_sha256' => hash_file('sha256', $fixtureDir . '/composer.fixture.json') ?: '(fixture)',
            'php_version' => '(fixture)',
            'composer_version' => '(fixture)',
            'solver' => 'in-process Composer dry-run',
        ]);
        $console = ReportFormat::Text->render($stable, true);

        return [
            'report.md' => "# $name — console report\n\nGenerated by `php bin/run-fixture.php $name --write-reports`; this is what `composer remediate` prints for this fixture.\n\n```text\n" . rtrim($console) . "\n```\n",
            'report.json' => ReportFormat::Json->render($stable, true),
            'report.html' => ReportFormat::Html->render($stable, true),
            'report.sarif' => ReportFormat::Sarif->render($stable, true, false, LockLineIndex::fromFile($fixtureDir . '/composer.fixture.lock')),
            'report.cdx.json' => (new CycloneDxRenderer(true, 'urn:uuid:00000000-0000-4000-8000-000000000000', '2026-01-01T00:00:00+00:00'))->render($stable),
            'gl-dependency-scanning-report.json' => (new GitLabRenderer(true, '2026-01-01T00:00:00', '2026-01-01T00:00:00'))->render($stable),
        ];
    }

    public static function write(Plan $plan, string $fixtureDir): void
    {
        @mkdir($fixtureDir . '/reports', 0755, true);
        foreach (self::render($plan, $fixtureDir) as $file => $contents) {
            file_put_contents($fixtureDir . '/reports/' . $file, $contents);
        }
        file_put_contents(self::COMPOSER_VERSION_FILE, self::minor(Composer::getVersion()) . "\n");
    }

    /**
     * The minor release the stored reports were recorded with, e.g. "2.10".
     */
    public static function recordedWith(): string
    {
        $recorded = trim((string) @file_get_contents(self::COMPOSER_VERSION_FILE));
        if ($recorded === '') {
            throw new \RuntimeException(self::COMPOSER_VERSION_FILE . ' is missing; run bin/run-fixture.php <fixture> --write-reports');
        }

        return $recorded;
    }

    public static function minor(string $version): string
    {
        return preg_match('{^(\d+\.\d+)}', $version, $m) === 1 ? $m[1] : $version;
    }
}
