<?php

declare(strict_types=1);

namespace Remediate\Tests\Support;

use Composer\Composer;
use Remediate\Engine\Plan\Plan;
use Remediate\Output\CycloneDxRenderer;
use Remediate\Output\GitLabRenderer;
use Remediate\Output\LockLineIndex;
use Remediate\Output\ReportFormat;

/**
 * The example reports stored under each fixture's reports/ directory, rendered in one place.
 *
 * bin/run-fixture.php --write-reports writes them and FixtureTest compares them with a fresh render,
 * both through render(), so the stored copy cannot drift from what the tool prints without a test
 * failing. The Composer release they were recorded with is stored beside them: an older Composer
 * (the Composer-version matrix) legitimately recommends different commands, so the comparison runs
 * only on the recorded minor release, and a newer one fails until the reports are regenerated.
 */
final class FixtureReports
{
    public const COMPOSER_VERSION_FILE = FixtureRunner::FIXTURE_ROOT . '/reports-composer-version.txt';

    /**
     * @return array<string, string> file name under reports/ => contents
     */
    public static function render(Plan $plan, string $fixtureDir): array
    {
        $name = basename($fixtureDir);
        $stable = $plan->withMetadata([
            'project' => $name,
            'advisory_source' => 'advisory snapshot advisories.json',
            'analysis_timestamp' => '(fixture)',
            // The checkout's bytes, not the scratch copy's: those depend on the line endings git chose.
            'composer_json_sha256' => self::hash($fixtureDir . '/composer.fixture.json'),
            'composer_lock_sha256' => self::hash($fixtureDir . '/composer.fixture.lock'),
            // dev-main locally, dev-<sha> on a pull request: which checkout ran it is not part of the example.
            'engine_version' => '(fixture)',
            'php_version' => '(fixture)',
            'composer_version' => '(fixture)',
            'solver' => 'in-process Composer dry-run',
        ]);
        $console = ReportFormat::Text->render($stable, true);

        return array_map(self::machineIndependent(...), [
            'report.md' => "# $name — console report\n\nGenerated by `php bin/run-fixture.php $name --write-reports`; this is what `composer remediate` prints for this fixture.\n\n```text\n" . rtrim($console) . "\n```\n",
            'report.json' => ReportFormat::Json->render($stable, true),
            'report.html' => ReportFormat::Html->render($stable, true),
            'report.sarif' => ReportFormat::Sarif->render($stable, true, false, LockLineIndex::fromFile($fixtureDir . '/composer.fixture.lock')),
            'report.cdx.json' => (new CycloneDxRenderer(true, 'urn:uuid:00000000-0000-4000-8000-000000000000', '2026-01-01T00:00:00+00:00'))->render($stable),
            'gl-dependency-scanning-report.json' => (new GitLabRenderer(true, '2026-01-01T00:00:00', '2026-01-01T00:00:00'))->render($stable),
        ]);
    }

    /**
     * Composer's conflict explanations name the PHP binary that ran the solve ("overridden via
     * config.platform, actual: 8.5.5"). That is right for a user and noise for a stored example, which
     * must be the same whichever PHP the suite runs on.
     */
    private static function machineIndependent(string $report): string
    {
        return (string) preg_replace('{(overridden via config\.platform, actual: )\d+\.\d+\.\d+[^\s),"<\\\\]*}', '$1(fixture)', $report);
    }

    /** A manifest's hash with line endings normalised, so a Windows checkout's CRLF does not change it. */
    private static function hash(string $path): string
    {
        $bytes = @file_get_contents($path);

        return $bytes === false ? '(fixture)' : hash('sha256', str_replace("\r\n", "\n", $bytes));
    }

    public static function write(Plan $plan, string $fixtureDir): void
    {
        @mkdir($fixtureDir . '/reports', 0755, true);
        foreach (self::render($plan, $fixtureDir) as $file => $contents) {
            file_put_contents($fixtureDir . '/reports/' . $file, $contents);
        }
        file_put_contents(self::COMPOSER_VERSION_FILE, self::minor(Composer::getVersion()) . "\n");
    }

    /**
     * The minor release the stored reports were recorded with, e.g. "2.10".
     */
    public static function recordedWith(): string
    {
        $recorded = trim((string) @file_get_contents(self::COMPOSER_VERSION_FILE));
        if ($recorded === '') {
            throw new \RuntimeException(self::COMPOSER_VERSION_FILE . ' is missing; run bin/run-fixture.php <fixture> --write-reports');
        }

        return $recorded;
    }

    public static function minor(string $version): string
    {
        return preg_match('{^(\d+\.\d+)}', $version, $m) === 1 ? $m[1] : $version;
    }
}
